"""add analysis fields, precedents, actions tables

Revision ID: 480952367899
Revises: 811160a0566c
Create Date: 2026-09-11 21:05:55.338363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '480952367899'
down_revision: Union[str, Sequence[str], None] = '811160a0566c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('corrective_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('report_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corrective_actions_report_id'), 'corrective_actions', ['report_id'], unique=False)
    op.create_table('historical_precedents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('reports', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('barrier_category', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('equipment_tag', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('site_tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'site_tag')
    op.drop_column('reports', 'equipment_tag')
    op.drop_column('reports', 'barrier_category')
    op.drop_column('reports', 'risk_score')
    op.drop_table('historical_precedents')
    op.drop_index(op.f('ix_corrective_actions_report_id'), table_name='corrective_actions')
    op.drop_table('corrective_actions')
    # ### end Alembic commands ###
