"""add fingerprint field to reports

Revision ID: 9cae13e1d89c
Revises: 2e3ca017470b
Create Date: 2026-09-14 02:45:49.524620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cae13e1d89c'
down_revision: Union[str, Sequence[str], None] = '2e3ca017470b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('fingerprint', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'fingerprint')
    # ### end Alembic commands ###
