"""add sif_probability and risk_level to reports

Revision ID: ca9315465692
Revises: dedf11ae5b90
Create Date: 2026-09-12 10:37:04.441173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca9315465692'
down_revision: Union[str, Sequence[str], None] = 'dedf11ae5b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('sif_probability', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('risk_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'risk_level')
    op.drop_column('reports', 'sif_probability')
    # ### end Alembic commands ###
