#!/bin/sh
# Sanketak first-run setup.
#
#   ./scripts/setup.sh
#
# Creates the two .env files a fresh clone needs. Safe to re-run: existing
# files are never overwritten, only reported.
set -e

cd "$(dirname "$0")/.."

echo "Sanketak setup"
echo "--------------"

# --- backend -----------------------------------------------------------
if [ -f .env ]; then
    echo "  .env                already exists, left alone"
else
    cp .env.example .env
    echo "  .env                created from .env.example"
    echo "                      -> EDIT IT: it needs a real OPENAI_API_KEY,"
    echo "                         or every extraction will fail."
fi

# --- mobile ------------------------------------------------------------
# A phone is not the machine running Docker, so "localhost" would resolve to
# the phone itself. The app has to be told this machine's address on the LAN.
LAN_IP=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)

if [ -z "$LAN_IP" ]; then
    LAN_IP=$(hostname -I 2>/dev/null | awk '{print $1}')
fi

if [ -z "$LAN_IP" ]; then
    LAN_IP="localhost"
    echo "  !  Could not detect a LAN IP. Using localhost, which works only in"
    echo "     a simulator on this machine. Set EXPO_PUBLIC_API_BASE_URL in"
    echo "     mobile/.env by hand to test on a real phone."
fi

if [ -f mobile/.env ]; then
    echo "  mobile/.env         already exists, left alone"
    echo "                      current: $(grep EXPO_PUBLIC_API_BASE_URL mobile/.env || echo 'not set')"
else
    cat > mobile/.env <<INNER
# Generated by scripts/setup.sh on $(date +%Y-%m-%d).
# Re-run the script (after deleting this file) if your IP changes.
EXPO_PUBLIC_API_BASE_URL=http://$LAN_IP:8000
EXPO_PUBLIC_USE_MOCK_VOICE_API=true
INNER
    echo "  mobile/.env         created, backend at http://$LAN_IP:8000"
fi

echo ""
echo "Next:"
echo "  1. Put a real OPENAI_API_KEY in .env"
echo "  2. docker compose up -d --build"
echo "  3. Dashboard:  http://localhost:8000/dashboard/"
echo "  4. App:        cd mobile && npm install --legacy-peer-deps && npx expo start"
